apiVersion: apps/v1
kind: Deployment
metadata:
  name: railway-booking-app
  namespace: railway-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: railway-booking
  template:
    metadata:
      labels:
        app: railway-booking
    spec:
      containers:
      - name: railway-app
        image: railwayacr.azurecr.io/railway-booking-system:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: railway-booking-service
  namespace: railway-system
spec:
  type: LoadBalancer
  selector:
    app: railway-booking
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Namespace
metadata:
  name: railway-system